init:
  - git config --global core.autocrlf true
version: '2.2.{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
nuget:
  disable_publish_on_pr: true
artifacts:
  - path: 'RequireJsNet\bin\**\*.nupkg'
  - path: 'RequireJsNet.Compressor\bin\**\*.nupkg'
  - path: 'RequireJsNet.ResxToJs\bin\**\*.nupkg'